### ISSUE TITLE
dcterms:license instead of gist:license

### ISSUE THREAD

**Issue by marksem** [semanticarts/gist#155]
I noticed we created a `gist:license` annotation property to point at a license URL.

Why not use existing term `dcterms:license`?  

Refs:
[1]  https://www.dublincore.org/resources/userguide/publishing_metadata/#dcterms:license

**Comment by rjyounes** [comment]
@marksem These three labels are meant to be mutually exclusive reasons for closing the issue. Which is it? And why NOT use dcterms:license? I would prefer it.

**Comment by marksem** [comment]
haha, those labels were NOT what I picked. :O  Some weird UI error, perhaps?  I fixed them (should be small, minor, patch).  My intent was to suggeste that we SHOULD use dcterms:license.

**Comment by rjyounes** [comment]
Sorry to persist, but minor and patch are also mutually exclusive. Did you mean to assign a priority instead?

I think it's a patch, doesn't affect semantics.

**Comment by uscholdm** [comment]
One reason to not use dcterms:license is to keep Rebecca happy by giving protégé no ideas about creating extra junk.  Kidding aside, I'm good with this.  Maybe a solution to the proptégé problem is to have a single ontology called say gistExternallyImported which has all the stuff that we use from outside ontologies.  This would be handy for all of us, a place to look for what external stuff is being used.

**Comment by rjyounes** [comment]
That doesn't solve the Protégé problem. Let's say you use dcterms:license in an owl file, even though you are not defining it. Protégé adds the following:

```
<owl:ObjectProperty rdf:about="&dcterms;license"/>
```

Caveat: dcterms is an rdf property, not an owl property, and I don't actually know how Protégé will dump this out (and won't take 5 minutes to test ;) ). So the problem is in the files that reference the property.

But @uscholdm I appreciate the thought. 

For the purpose of helping to keep track, I've done something a bit different, which is to create a directory called sources and add fragments of external ontologies (whether imported or not), one per file. Makes things a little clearer.

**Comment by DanCarey404** [comment]
I think we need a discussion about whether or not gist is to be self-contained.  And if not, to what extent are we willing to rely on external ontologies.  I definitely think Dave needs to weigh in on that question.

**Comment by DanCarey404** [comment]
Also, dcterms:license is an object property, not an annotation.  Does that make any difference in this case?

**Comment by rjyounes** [comment]
I agree on both counts, that this is a bigger discussion and that Dave should be involved.

To be strictly accurate, dcterms is an rdf ontology, not an owl ontology. You could loosely say it functions like an object property because it has a non-literal value, but it will not be included in owl inferencing - this might allay the concern about it not being an annotation.

**Comment by rjyounes** [comment]
Opened issue #161 to address issue more generally.

**Comment by rjyounes** [comment]
We decided not to use RDF properties in issue #389.
